# 1. Database Configuration (Telling Spring to use the H2 in-memory DB)
spring.datasource.url=jdbc:h2:mem:librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Tell Hibernate to automatically create the tables based on our Java classes
spring.jpa.hibernate.ddl-auto=update

# Enable the H2 web console so we can look at our database later (Optional but helpful)
spring.h2.console.enabled=true

# 2. View Resolver Configuration (Telling Spring MVC where to find the UI)
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
# Tells Spring to wait until Hibernate creates the tables before running data.sql
spring.jpa.defer-datasource-initialization=true
